### PR TITLE
Generalized the implementation of the player, so that we can implement more animals.

### PR DESCRIPTION
**Pull request by Hifoz**
Currently, the animal you start with is randomized, as a character select screen isn't yet implemented. The models for the players also won't always be the same on the different clients, because I assign the animal randomly when initializing the PlayerCharacter, and I can't really control when other clients have their animal set at the moment. This probably won't be an issue when we get a character select screen though.

Also, changed deprecated Random.RandomRange() to Random.Range()

_Just testing how the pull requests work, rather than just merging it straight in._

### CODE REVIEW

**Comment by adamajammary** [comment]
**ERROR:**
NullReferenceException: Object reference not set to an instance of an object
PlayerController.shoot () (at Assets/Scripts/PlayerController.cs:59)
PlayerController.Update () (at Assets/Scripts/PlayerController.cs:51)

**SOLUTION:**
Make sure "_bunnyCommands != nullptr".

Only the bunny has this component, when the fox is loaded this component is missing. We can make it more flexible later, or add a fox commands script etc., but for now we can just make sure "_bunnyCommands != nullptr" inside the shoot function (line 59).

**Comment by Hifoz** [comment]
Yes, this is because the PlayerController script currently handles the controls for everything, even if they are specific for a single animal. I would think the best way to deal with it would be to move animal-specific actions to seperate Components (BunnyController, FoxController, etc..) that can be added when setting up the player as that animal.

I'll look into moving the animal specific actions into seperate controllers and update the pull-request.

**Comment by Hifoz** [comment]
Errors should now be gone, and all things specific for an animal goes into its own controller.

**Comment by adamajammary** [comment]
Looking good, errors are gone, and we are now ready for the future :)
This Pull Request is ready to be merged unless anyone else found any issues.

**Review by adamajammary — APPROVED** [review]
OK, ready to be merged.

**Pull request merged**
