### PR TITLE
Planning NPCs

### PR DESCRIPTION
**Pull request by Muff1nz**
- NPCs now use A* to path around obstacles.
- NPCs are better at fleeing from danger (if you don't kill them they'll pile up in the center late game, due to the wall surrounding them).
- NPCs are now proper FSM agents.
- Improved NPCWorldView map, NPCs are now less prone to falling into water.

NB! New .nwl files, so regenerate them in your build, should only take 10 secs. 

Syncing is a bit wonky, because having to sync a path is harder then what had to be synced before. 
In the future i might try calculating the path every update and just moving one step towards the goal at a time, this wont slow down fps as the main thread never waits for the NPCThread anymore, the consequence would be NPCs that need more time to react.

### CODE REVIEW

**Comment by Muff1nz** [comment]
The fire particle effect isn't visible behind the wall for me anymore, i think it's because i reinstalled windows, so i now have a newer version of unity.

Because i havent done anything graphics related with this PR.

If that's the case then i'll just install the old unity version.

**Comment by Hifoz** [comment]
There seems to be a bug that makes all the npc stop making decisions and just keep walking in the same direction constantly.

**Comment by Hifoz** [comment]
Also, the editor is hanging up again

**Comment by Muff1nz** [comment]
I had those issues earlier today, but i fixed them. The main thread never loops waiting for the NPCThread anymore so the editor hanging sounds weird.

**Comment by Muff1nz** [comment]
Have any info on how to reproduce?

**Comment by Hifoz** [comment]
The hanging happens every time I try to start the game(in editor) for a second time after quitting. The npcs stopping to work just happens as I play, without me doing anything special.

**Comment by Muff1nz** [comment]
Can't reproduce it

**Comment by Hifoz** [comment]
Could be a version specific thing? I am on 1.1f1, while you are on 2.0f3 according to your changes to ProjectVersion.txt.

I'll try updating to the newest version and see if the issue continues

**Comment by Hifoz** [comment]
Issue seems to still be there after updating to 2.0f3. However I noticed that the editor hanging only happens if I quit after the npcs stop working.

**Comment by Muff1nz** [comment]
Can't reproduce the stopping thing, see if this helps

**Comment by Hifoz** [comment]
Didn't change anything.

**Comment by Muff1nz** [comment]
Does it happen often?

**Comment by Muff1nz** [comment]
Does your NPC map look normal? You can check by clicking the debug boxes in the NPCManager gameobject

**Comment by Muff1nz** [comment]
image
This is how mine looks

**Comment by Hifoz** [comment]
How do I check that?

Edit: Found it. Looks normal

**Comment by Muff1nz** [comment]
Select the NPCManager in the scene view on the island, then click Debug Render Land on the NPC World View Manager script.

**Comment by Muff1nz** [comment]
Okay, does the last commit do anything?

**Comment by Hifoz** [comment]
Looks to be working now. Will do another couple of tests just to be sure though

**Comment by Hifoz** [comment]
Just tested with multiple clients, the npcs are extremely jumpy for the non-host players

**Comment by Muff1nz** [comment]
Yeah, the PR mentions it

**Comment by Hifoz** [comment]
My bad, didn't notice that.

**Review by Hifoz — APPROVED** [review]
Looks good then.

**Pull request merged**
