### PR TITLE
Added playernames

### PR DESCRIPTION
**Pull request by Hifoz**
Added a PlayerInformation class,  which contains the clientID of a player, as well as the players name.
The name is synced over the network and has been tested both on localhost and internet servers.

NB! Name cannot contain X because the network manager hud uses that as a shortcut to leave the room...

### CODE REVIEW

**Comment by Muff1nz** [comment]
Problem: Bunnies can't damage eachother with normal attacks, there is blood however.
This does not happen on master

**Comment by adamajammary** [comment]
Getting PlayerInfo from projectile (other) instead of the player who instantiated the projectile.

PlayerEffects.cs:74 => PlayerInformation otherInfo = other.GetComponent<PlayerInformation>();
PlayerEffects.cs:77 => otherInfo is NULL

**Comment by Muff1nz** [comment]
Yeah, can use the projectiles owner attribute, which is a reference to the gameobject that shot it

**Comment by Hifoz** [comment]
The bunnypoop should now deal damage properly

**Review by Muff1nz — APPROVED** [review]
I trust you  👍

**Pull request merged**
