### PR TITLE
Reworked fox stealth ability

### PR DESCRIPTION
**Pull request by Hifoz**
* The fox now appears 100% invisible for other players when using stealth ability (still visible on local player though, so that you can actually see yourself) (movement sound isn't removed completely) 
* The stealth ability now cancels when attacking
* Cooldown was changed from 10 to 15 seconds while the active time was changed from 10 to 7 seconds

### CODE REVIEW

**Comment by Muff1nz** [comment]
I can't use the stealth ability

**Comment by Muff1nz** [comment]
image
 It looks like this

**Comment by Hifoz** [comment]
Apparently I had set the wrong variable, it should work again now

**Review by Muff1nz — APPROVED** [review]
Looks cool.

**Pull request merged**
