### PR TITLE
NPCs fear fire

### PR DESCRIPTION
**Pull request by Muff1nz**
- NPCs will now try to escape the wall.
- The generation of .nwl files now has a progress bar, takes me about 60s to generate them.
- Misc.

### CODE REVIEW

**Comment by Muff1nz** [comment]
Trying to merge

**Comment by Hifoz** [comment]
Is the generation of .nwl files supposed to be unity-editor only?
Edit:
Also, I had to remove the lobby scene from the build settings and re-add it to be able to build the project.

**Comment by Muff1nz** [comment]
Just found an issue, killing all NPCs freezes the game
The generation isn't editor only, maybe you have the files in the build?

**Comment by Hifoz** [comment]
I tried building to a clean location, and it didn't generate the files, just got a world with no npcs

**Comment by Muff1nz** [comment]
Yeah, tried it now, me2

**Comment by Hifoz** [comment]
I would also suggest changing the message shown when generating to something more user friendly, like "NPC map could not be found, generating..." or something like that.

**Comment by Hifoz** [comment]
It now seems to generate the files also in stand-alone, but it only saves them if the folders are set up (Assets/Data/)

**Comment by Muff1nz** [comment]
That's fine

**Review by Hifoz — APPROVED** [review]
looks good

**Pull request merged**
