### PR TITLE
Player Attributes

### PR DESCRIPTION
**Pull request by Muff1nz**
- Players now have attributes (Toughness, damage, speed, jumping).
- The attributes works like multipliers for the associated actions.
- The attributes have an UI in the bottom left corner.
- Turtles are now chickens.
- Playerhealth is now a float instead of an int.
- NPCs escape players without having a seizure. 

You can't steal attributes from NPCs yet, thats coming next.

### CODE REVIEW

**Comment by Muff1nz** [comment]
~~Just found an issue with the UI, hol up~~

**Review by adamajammary — APPROVED** [review]
loooks good

**Review by Hifoz — CHANGES_REQUESTED** [review]
Problem:
Your chickens seems to have the same rendering bug that the fox had previously, because of the materials
Fix:
The chickens need the CorrectRenderingMode function in the PlayerController. This function was there previously when we still used the Turtle model

**Comment by Muff1nz** [comment]
I know, you can see their feet, they're just like that i think

**Comment by Muff1nz** [comment]
Unity set the rendering mode on the chicken to fade when importing for some reason.

**Comment by Hifoz** [comment]
You have now broken the fox' stealth ability. For some reason the chick is using the same materials as the fox

**Comment by Muff1nz** [comment]
Oh, then thats why they were set to fade

**Review by Hifoz — APPROVED** [review]

**Pull request merged**
