### PR TITLE
Fall Damage

### PR DESCRIPTION
**Pull request by Hifoz**
The player can take fall damage if falling far enough.  
No damage when falling into water.  
Made the player immune from damage for 5 seconds after spawning. This will make it so the initial fall won't damage the player. Also nice to not have to worry about dying the second you spawn in.

### CODE REVIEW

**Comment by adamajammary** [comment]
Problem: it will only run the damageImmune co-routine once in Start, and not when player re-spawns.
Fix: It will run when re-spawning as well if you run it in the RpcSpawn function as well (since re-spawn doesn't actually re-create the player and re-start the script, it only re-sets their health and position).

**Comment by adamajammary** [comment]
Sorry, it needs to run in both places ;) once in Start and once in RpcRespawn.
1) The player is instantiated and spawned in NetworkPlayerSelect::OnLobbyServerCreateGamePlayer
2) The PlayerHealth script loads and Start runs
3) The player dies and re-spawns in the RpcRespawn function

**Comment by Hifoz** [comment]
Whoops! Though it ran on start as well because I wasn't taking damage on the initial fall, but that was because I had initialized _damageImmune to true and it was never set back to false...

**Comment by adamajammary** [comment]
works perfectly fine.

**Comment by Hifoz** [comment]
[fall damage](https://trello.com/c/89VGvUbI/47-fall-damage)

**Pull request merged**
