### PR TITLE
NPC improvements

### PR DESCRIPTION
**Pull request by Muff1nz**
- NPCs behave more naturally, they're better at avoiding obstacles, they'll avoid players when not avoiding obstacles, and otherwise roam around freely. 
- NPCs no longer spawn in water (mostly, can improve by cranking up resolution of NPCWorldView, at the cost of performance).
- A map of the water for NPCs.
- NPCWorldView is now loaded from a file to reduce start up time, if the file doesn't exist it will be generated.
- Dead players/npcs are now handeled and removed from datastructures.
- Performance improvements.

### CODE REVIEW

**Comment by Hifoz** [comment]
Issue:
Something's broken, but I don't have the slightest clue what... Maybe threading-linked?  
\---
How to replicate:
1. I start the game in editor and open a server
2. I close the server by pressing the X-key
3. I close the game
3. I go File->Build and run
4. Build finishes
5. Unity editor freezes? Have to restart the editor.  

\---
(This does not occur when on master branch btw.)

**Comment by Muff1nz** [comment]
I was unable to replicate the issue. Could you try with a fresh clone of my branch?

**Comment by Hifoz** [comment]
Fresh clone seems to have fixed it

**Comment by Hifoz** [comment]
Never mind! Still does it...
I forgot to go into the repo before checking out your branch, so i was still on master

**Comment by Muff1nz** [comment]
What Unity version are you using? I'll update and try again if mine is older

**Comment by Hifoz** [comment]
my version is 2017.1.1f1

note that the bug only appears when closing the server before stopping the game

**Comment by Muff1nz** [comment]
When you say that you open a server, do you also go ingame before quitting?

**Comment by Hifoz** [comment]
yes, I wait for things to load up and give it a second before quitting

**Comment by Muff1nz** [comment]
Okay, i know what it is then, will commit a fix once the new Unity is installed

**Comment by Hifoz** [comment]
No longer freezing, so it's good to go.

**Pull request merged**
