### PR TITLE
Settings menu

### PR DESCRIPTION
**Pull request by Hifoz**
Added a functional settings panel.
The settings are saved to PlayerPrefs.

Resolution, window mode, vsync, mouse sensitivity and fov has been added with funtionality.
Sliders has also been added for audio control, but no functionality has been implemented for this as we still have no audio in the game.

### CODE REVIEW

**Comment by Muff1nz** [comment]
Looks good, one issue that i found: I can't play at my native resolution (2560x1440)

**Comment by Muff1nz** [comment]
Also, there's a merge conflict

**Comment by Hifoz** [comment]
Fixed merge conflicts, added 1440p resolution option and added settings to the ingame menu.

**Review by Muff1nz — APPROVED** [review]
Found no issues in my short test, +1

**Pull request merged**
