### PR TITLE
Make the player face the direction of the camera when in first person

### PR DESCRIPTION
**Pull request by Hifoz**

### CODE REVIEW

**Comment by adamajammary** [comment]
is it just me, or is the character facing/rotating in the opposite direction of the camera/aiming?

**Comment by Hifoz** [comment]
That's not happening for me, both the fox and the bunny are rotating properly here

**Comment by Hifoz** [comment]
But i did just notice it doesn't rotate when standing still. I'll see if I can do something about that

**Comment by adamajammary** [comment]
Everything works fine in FPP now, it faces in the right direction when exiting FPP mode.

When the character is standing still and rotating in normal mode (outside of FPP), 
it rotates/turns in the opposite direction, when the camera turns left, the character turns right and vice-versa. Does that happen for you as well? If yes, we can make a new issue and trello board. Otherwise I'll merge this PR since FPP mode works fine for me.

**Comment by Hifoz** [comment]
No, that doesn't happen for me. How are you rotating outside of FPP without moving? Isn't rotation (in normal mode) only done when you are moving?

**Comment by adamajammary** [comment]
I just stand still, move the mouse to the left, the camera faces left, the character as you said doesn't rotate, so it's facing right, then right-clicking it enters FPP and aiming is to the left, and when releasing right-click, the character correctly rotates and faces left (like the camera).

It's not really an issue, it has always been like this, nothing new. :)

I'll merge the PR.

**Comment by Hifoz** [comment]
Ah yes, now I know what you mean. This does indeed happen for me to, but that is because of how the Move() function was written. Personally I'd prefer that the rotation followed the cameras direction (like in FPP now), but I guess we can discuss that on monday.

**Pull request merged**
