### PR TITLE
improved firewall graphics, fixed scaling issue aswell

### PR DESCRIPTION
**Pull request by Muff1nz**
The firewall now kinda looks like pixel-art fire, also doesn't get "squished" when the wall shrinks

### CODE REVIEW

**Comment by Hifoz** [comment]
**Problem:**
```
Destroy can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
UnityEngine.Object:Destroy(Object)
Circle:Finalize() (at Assets/Scripts/FireWall.cs:144)
```

**Solution**: Don't have a custom destructor in Circle(). The wall will be destroyed anyways.

**Comment by Muff1nz** [comment]
The wall gameobject wont be destroyed unless Destroy is called on it

**Comment by Hifoz** [comment]
Are you sure? Because the wall is spawned using Instantiate, which should cause it to be destroyed automatically by the engine when leaving the scene.

**Comment by Muff1nz** [comment]
Yeah, im fixing the issue now. What i mean is that each time the wall shrinks and calls recalculate, a new mock wall is created in the scene. I was hoping that by using the deconstructor the wall would be destroyed when GC got the Circle object when it was no longer referenced.

**Pull request merged**
