### PR TITLE
Added Start Menu with working exit button and play button

### PR DESCRIPTION
**Pull request by magweng**
Run the  "StartScreen" scene first.

### CODE REVIEW

**Review by Muff1nz — DISMISSED** [review]
+1, looks really nice!

**Comment by adamajammary** [comment]
nice :)
PS! not sure if it's only me, but when I clicked on start/play, it was missing the name input that michael added.

**Comment by Muff1nz** [comment]
He hasn't merged
Just merge and we'll see.

**Review by adamajammary — APPROVED** [review]
All changes are in a separate scene, so there shouldn't be any conflicts with master.

**Pull request merged**
